# ========================
# Common Configuration
# ========================
spring.application.name=expense-tracker-backend

# JWT Configuration - Use environment variables in production
spring.security.jwt.secret=${JWT_SECRET}
spring.security.jwt.expiration=86400000  

# Server Configuration
server.port=${PORT}
server.servlet.context-path=/expense-tracker-api
server.error.whitelabel.enabled=true   

logging.level.com.expensetracker=${LOG_LEVEL}
logging.level.org.springframework.security=${LOG_LEVEL}

# Activate MySQL profile
spring.profiles.active=mysql

# Email Configuration - Use environment variables in production
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.email.from=${MAIL_FROM}
